global using NEPlumbingInc.Components;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authentication.Cookies;
global using System.Security.Claims;
global using Microsoft.AspNetCore.Components.Authorization;
global using System.ComponentModel.DataAnnotations;
global using NEPlumbingInc.Models;